[WIP] Add new email templates for the auth flow
dataswift/HAT2.0 pull request #172
Opened 2020-09-24 15:49 UTC by leymytel

Add new email templates for the new auth flow: 
- Email verification
- Reset password
- Password changed

**Please do not merge.**

2020-09-24 15:53 UTC, augustinas approved these changes

2020-09-24 15:55 UTC, augustinas requested changes
Blocking the PR because integration with Scala code needs to be completed.

2020-09-24 16:37 UTC, dataswifty approved these changes

2020-09-25 09:48 UTC, augustinas commented
Cancelling this PR and the changes have been merged into PR https://github.com/dataswift/HAT2.0/pull/173

2020-09-25 09:48 UTC, closed without merging