set up cors on lb
dataswift/HAT2.0 pull request #547
Opened 2021-09-01 17:07 UTC by pperzyna

## Description

Mandatory, provide a detailed description of the changes.

## Why

Optional i.e. "Why I have chosen package X, and not alternative package Y, Z"

## AC

Copy and paste from task

## Source

Link to story/task/bug

## Type

- [ ] Bug Fix
- [ ] Feature Addition
- [ ] Refactor
- [ ] HotFix

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2021-09-02 12:45 UTC, whiteshadow-gr approved these changes

2021-09-02 12:54 UTC, dataswifty requested changes
Please add a comment that says we have moved CORS into infra.

2021-10-04 12:09 UTC, augustinas reviewed
This PR still has a blocking review. @pperzyna @dataswifty can you resolve it? 
From my perspective I would add that any unused code should be removed rather than commented out.

2021-10-05 15:43 UTC, dataswifty commented on hat/conf/play.conf
> +//        "play.filters.cors.CORSFilter",
I would delete this.

2021-10-05 15:45 UTC, pperzyna commented on hat/conf/play.conf
> +//        "play.filters.cors.CORSFilter",
deleted

2021-10-05 15:45 UTC, merged